# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

env:
  springopsfile: springops/sample.yaml
  version: V1

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Create Draft Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.version }}
        release_name: TheArtifact
        draft: true
        prerelease: false
       
    
        
    - uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: target/springopsdemo-0.0.1-SNAPSHOT.jar
        asset_name: 'theartifact.jar'
        asset_content_type: application/jar

    - uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.create_release.outputs.id }}

    - uses: actions/checkout@v2
    - name: Find and Replace envversion
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "$$version$$"
        replace: ${{ env.version }}
        include: "springops/**"
        regex: true
    
    - name: Push Generated yaml file to repo springops-manifests
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
       API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
       source_file:  ${{ env.springopsfile }}
       destination_repo: 'felipmiguel/springops-manifests'
       destination_folder: '/'
       user_email: 'fmiguel@microsoft.com'
       user_name: 'felipmiguel'
       commit_message: Committing file ${{ env.springopsfile}}
        

